apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 2  # Increase redundancy
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - --no-autoupdate
          - run
          - --ha-connections
          - "4"
          - 2e4e840d-bdc7-4aa1-8d40-5d7f5df54f78  # Your Tunnel UUID
        volumeMounts:
          - name: config
            mountPath: /etc/cloudflared
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 20241
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 20241
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: cloudflared-config
              - secret:
                  name: cloudflared-credentials

