apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - run
          - --config
          - /etc/cloudflared/config.yaml
        volumeMounts:
          - name: config
            mountPath: /etc/cloudflared
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: cloudflared-config
              - secret:
                  name: cloudflared-credentials

