apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - --no-autoupdate
          - --protocol
          - http2
          - run
          - 2e4e840d-bdc7-4aa1-8d40-5d7f5df54f78
        volumeMounts:
          - name: config
            mountPath: /etc/cloudflared
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: cloudflared-config
              - secret:
                  name: cloudflared-credentials

