# apps/cns/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: default

patches:
  - target:
      kind: Deployment
      name: cns
    path: patch-deploy-cns.yaml

  - target:
      kind: Service
      name: cns
    path: patch-svc-cns.yaml

