# apps/react-portfolio/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: default

patches:
  - target:
      kind: Deployment
      name: react-portfolio
    path: patch-deploy-react-portfolio.yaml

  - target:
      kind: Service
      name: react-portfolio
    path: patch-svc-react-portfolio.yaml

  - target:
      kind: Deployment
      name: react-portfolio
    path: patch-readiness-react-portfolio.yaml

