apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-portfolio
spec:
  template:
    spec:
      containers:
        - name: react-portfolio
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 2

