# argo/cns-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cns
  namespace: argocd
spec:
  project: default

  source:
    # Update with your infra repo URL
    repoURL: https://github.com/nishanau/gitops-infra-k8s.git
    targetRevision: main
    path: apps/cns/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

