# argo/react-portfolio-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-portfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nishanau/gitops-infra-k8s.git
    targetRevision: main
    path: apps/react-portfolio/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

